version: 2.1

jobs:
  download_and_upload:
    docker:
      - image: cimg/node:18.17
    environment:
      TORRENT_MAGNET: "magnet:?xt=urn:btih:8F86D38E13D6D295477E3EBF05494A030333637A&dn=Ke+X.+Space-Time+Coding+Theory+in+Optical+Wireless+MIMO+Systems+2025&tr=udp://tracker.bittor.pw:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.dler.org:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://exodus.desync.com:6969/announce&tr=udp://open.demonii.com:1337/announce"
      PIXELDRAIN_API_KEY: "8ec6f000-e8d1-403d-820b-4324a6a68869"  # replace or use project env var
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            npm install webtorrent-cli

      - run:
          name: Download torrent
          command: |
            mkdir -p downloads
            npx webtorrent download "magnet:?xt=urn:btih:E2360B5BEB494200AF4FEE826CD8C66C668B9864&dn=Invader+ZIM+%282001%29+Season+1-2+S01-02+Specials+%281080p+DVD+AI+UPSACLE+x265+HEVC+10bit+DD+2.0+EDGE2020%29&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce" --out ./downloads --quiet

      - run:
          name: Upload files to PixelDrain
          command: |
            find ./downloads -type f | while read -r FILE; do
              echo "Uploading $FILE..."
              curl -T "$FILE" -u :$PIXELDRAIN_API_KEY https://pixeldrain.com/api/file/
            done

workflows:
  version: 2
  download_and_upload_workflow:
    jobs:
      - download_and_upload

