name: Torrent Download & Upload to Pixeldrain

on:
  push:
    branches:
      - new
  workflow_dispatch:

jobs:
  torrent-upload:
    runs-on: ubuntu-latest
  # Replace with your actual API key
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g webtorrent-cli 
          pip install requests 
          
      - name: Download torrent content with webtorrent-cli
        run: |
          mkdir downloads
          webtorrent download "magnet:?xt=urn:btih:8b7f95d50ed9877096a78d0baf1c1960c9420ce2&dn=Murder%20By%20Medic%20S04E07%20Jacob%20Hoysted%20720p%20AMZN%20WEB-DL%20DDP2%200%20H%20264-RAWR%5BEZTVx.to%5D.mkv%5Beztv%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce" --out downloads

      - name: Run your koofr upload
        run: |
          find downloads -type f -print0 | while IFS= read -r -d '' file; do
                curl -X POST "https://upload.gofile.io/uploadfile" \
                     -H "Authorization: Bearer NkEP9nPmjC5bYQB7ZabZKnsUEBi7ww85" \
                     -F "file=@\"$file\"" \
                     -F "folderId=569169f0-479c-4720-857a-2aa341d5eca9"
              done
