name: Torrent Download & Upload to Pixeldrain

on:
  push:
    branches:
      - Download
  workflow_dispatch:

jobs:
  torrent-upload:
    runs-on: ubuntu-latest
    env:
      TORRENT_TORRENT_URL: 'https://itorrents.org/torrent/27F160798A82E23608607455EB4064309C99DD63.torrent'
      PIXELDRAIN_API_KEY: '8ec6f000-e8d1-403d-820b-4324a6a68869'  # Replace with your actual API key
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install -g webtorrent-cli

      - name: Create dummy file with brackets in name
        run: |
          mkdir -p ./dummy_files
          echo "This is a dummy file" > "./dummy_files/My Love [EZTVx.to].mkv"

      - name: Download torrent file if not exists
        run: |
          if [ ! -f ./torrent/file.torrent ]; then
            mkdir -p ./torrent
            wget -O ./torrent/file.torrent "$TORRENT_TORRENT_URL"
          else
            echo "Torrent file already exists, skipping download."
          fi

      - name: Download torrent content with webtorrent-cli
        run: |
          webtorrent download ./torrent/file.torrent --out ./downloaded_files --quiet

      - name: Upload dummy file with brackets (escaped during upload)
        run: |
          file="./dummy_files/My Love [EZTVx.to].mkv"
          filename=$(basename "$file")

          # Prepare escaped filename for curl -T if needed
          # (Note: curl uses the actual filename; escaping is only for filename display purposes here)
          
          echo "Uploading $filename..."
          
          # Upload dummy file
          curl -globoff -T "$file" -u :$PIXELDRAIN_API_KEY "https://pixeldrain.com/api/file/"

      - name: Upload all downloaded files (escape brackets during upload)
        run: |
          find ./downloaded_files -type f | while read -r file; do
            filename=$(basename "$file")
            escaped_filename="$filename"
            # Escape brackets in filename
            if [[ "$filename" == *"["* || "$filename" == *"]"* ]]; then
              escaped_filename="${filename//\[/\\[}"
              escaped_filename="${escaped_filename//\]/\\]}"
            fi
            echo "Uploading $filename..."
            # Upload the file
            curl -globoff -T "$file" -u :$PIXELDRAIN_API_KEY "https://pixeldrain.com/api/file/"
          done
