name: Create and Upload File with Brackets

on:
  push:
    branches:
      - New

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create file with brackets in name
        run: |
          echo "This is a test file" > hsjsks\[EZTVx.to\].mkv

      - name: Upload file with backslashes escaped
        run: |
          curl -T hsjsks\\[EZTVx.to\\].mkv -u :8ec6f000-e8d1-403d-820b-4324a6a68869 https://pixeldrain.com/api/file/
