name: Torrent Download & Upload to Pixeldrain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  torrent-upload:
    runs-on: ubuntu-latest
    env:
      TORRENT_TORRENT_URL: 'https://itorrents.org/torrent/27F160798A82E23608607455EB4064309C99DD63.torrent'
      PIXELDRAIN_API_KEY: '8ec6f000-e8d1-403d-820b-4324a6a68869'  # Replace with your actual key
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget nodejs npm
          npm install -g webtorrent-cli

      - name: Create directories
        run: |
          mkdir -p ./torrent
          mkdir -p ./downloaded_files

      - name: Create dummy file with complex filename before torrent download
        run: |
          echo "Dummy content" > "./downloaded_files/sample file [EZTVX.TO].txt"

      - name: Upload dummy file to Pixeldrain
        run: |
          echo "Uploading dummy file..."
          curl -T "./downloaded_files/sample file [EZTVX.TO].txt" -u :$PIXELDRAIN_API_KEY https://pixeldrain.com/api/file/
          echo "Dummy file uploaded."

      - name: Download torrent file if not exists
        run: |
          if [ ! -f ./torrent/file.torrent ]; then
            wget -O ./torrent/file.torrent "$TORRENT_TORRENT_URL"
          else
            echo "Torrent file already exists, skipping download."
          fi

      - name: Download torrent content with webtorrent-cli
        run: |
          webtorrent download ./torrent/file.torrent --out ./downloaded_files --quiet

      - name: Upload all files in downloaded_files to Pixeldrain
        run: |
          find ./downloaded_files -type f | while read -r file; do
            filename=$(basename "$file")
            echo "Uploading \"$filename\"..."
            curl -T "$file" -u :$PIXELDRAIN_API_KEY https://pixeldrain.com/api/file/
            echo "Uploaded \"$filename\""
          done
